# Use an existing base image
FROM nginx:alpine

# Set the working directory in the container
WORKDIR /usr/share/nginx/html

# Copy the contents of the current directory into the container at the working directory
COPY . .

# Expose port 80 to allow external access to the web server
EXPOSE 80
